version: '3'

services:
  app:
    build: 
      context: ./node
    container_name: app
    restart: unless-stopped
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "npm start"
    volumes:
      - app-volume:/usr/src/app
    networks:
      - app-network
    environment:
      - PORT=3000
      - HOST=db
      - USER=root
      - PASSWORD=root
      - DATABASE=nodedb
    ports:
      - "3000:3000"
    depends_on: 
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - db-volume:/var/lib/mysql/:rw
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-volume:
  db-volume:
      
