version: '3'

services:
  app:
    build: 
      context: ./node
    container_name: app
    restart: unless-stopped
    volumes:
      - ./node:/usr/src/app
    networks:
      - app-network
    environment:
      - PORT=8080
    ports:
      - "3000:8080"
    depends_on: 
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - /mysql:/var/lib/mysql/:rw
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      
